name: Build and deploy JAR app to Azure Web App - letsmeeet

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      working-directory: ./BackEnd
      run: mvn clean install -Pprod

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'letsmeeet'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_F31BD02825904E5AA22E51C7C317896 }}
        package: '${{ github.workspace }}/BackEnd/target/*.jar'
